##############################################
#                                            #
#           Superfile Configuration          #
#                                            #
##############################################

# This contains the root config file for superfile! More details can be found at
# https://superfile.dev/configure/superfile-config/.

###############################################################################
#                                   Defaults                                  #
###############################################################################

#-- File Editor
# Default: $EDITOR
editor = "zeditor"
dir_editor = "zeditor"
auto_check_update = true
cd_on_quit = false
default_open_file_preview = true
show_image_preview = true
show_panel_footer_info = true
default_directory = "."
file_size_use_si = false

#-- Default File Sort Type
# (0: Name, 1: Size, 2: Date Modified, 3: Type).
default_sort_type = 0
sort_order_reversed = false

#-- Case-Sensitive Sorting (only for Name Sort)
# An uppercase "B" comes before a lowercase "a" if true.
case_sensitive_sort = false

#-- Exit Shell on Success
# Whether to exit the shell on successful command execution.
shell_close_on_success = false

#-- Page Scroll Size
# Number of lines to scroll for PgUp/PgDown keys (0: full page, default behavior).
page_scroll_size = 0
debug = false

#-- Ignore Missing Config Fields
# Whether to silence any warnings about missing config fields.
ignore_missing_fields = false

#-- File Panel Extra Columns Count
# Count of extra columns in file panel in addition to file name. When option equal 0 then feature is disabled.
file_panel_extra_columns = 0

#-- File name width in File Panel
# Percentage of file panel width allocated to file names (25-100). Higher values give more space to names, less to extra columns.
file_panel_name_percent = 50


###############################################################################
#                                   Styling                                   #
###############################################################################

#-- Theme
# Put your theme's name here!
theme = "catppuccin-mocha"

#-- Code Previewer
# Whether to use the builtin syntax highlighting with chroma or use bat. Values: "" for builtin chroma, "bat" for bat
code_previewer = ""
nerdfont = true
show_select_icons = true
transparent_background = false
file_preview_width = 0
enable_file_preview_border = false
sidebar_width = 20
border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'

###############################################################################
#                                   Plugins                                   #
###############################################################################

# This section is for using plugins with superfile, external addons that extend
# the default capabilities of the program! More info can be found at
# https://superfile.dev/list/plugin-list/.

#-- Detailed Metadata
# Requires: exiftool
metadata = false

#-- MD5 Checksum Generation
# Requires: md5sum
enable_md5_checksum = false
#
#-- Zoxide Support - Smart directory navigation!
# Requires: zoxide
zoxide_support = false

#-- File opening rules
# Map file extensions to commands used to open them.
# The file path will be appended as the last argument.
# MUST BE IN THE VERY END OF THE FILE BECAUSE TOML CANNOT CLOSE TABLES
# Example:
#   png = "feh"
#   pdf = "zathura"
#   conf = "nvim"
[open_with]
