"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$c\
$cpp\
$rust\
$nodejs\
$java\
$kotlin\
$python\
$dart\
$git_branch\
$git_status\
$time\
[ÓÇ∞ ](fg:color_bg1)\
$line_break$directory$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_c = '#085EA0'

[os]
disabled = false
style = "bg:color_blue fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
Mint = "Û∞£≠"
Linux = "Û∞åΩ"
Fedora = "Û∞£õ"
Android = "Óúé"
Arch = "Û∞£á"
EndeavourOS = "ÔÜó"

[username]
show_always = true
style_user = "bg:color_blue fg:color_fg0"
style_root = "bg:color_blue fg:color_fg0"
format = '[ $user ]($style)'

[directory]
format = "[$path ]($style)"
truncate_to_repo = true
home_symbol = "Û∞ãû"

[directory.substitutions]
"documents" = "Û∞àô"
"downloads" = "ÔÄô"
"music" = "Û∞ùö"
"pictures" = "ÔÄæ"
"programming" = "ÔÑ°"
"games" = "Û∞äó"

[git_branch]
symbol = "Ôêò"
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = "Óúò"
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_green)]($style)'

[c]
symbol = "Óòû "
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_c)]($style)'

[cpp]
symbol = "Óòù "
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_c)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red)]($style)'

[kotlin]
symbol = "Óò¥"
style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red)]($style)'

[python]
symbol = "ÓòÜ"
# style = "bg:color_red"
format = '[[ $symbol( $version) \($virtualenv\) ](fg:color_fg0 bg:color_yellow)]($style)'

[dart]
symbol = "üéØ"
# style = "bg:color_red"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:#0A5997)]($style)'

[time]
disabled = false
time_format = "%r"
style = "bg:color_bg1"
format = '[[ Ôê∫ $time ](fg:color_fg0 bg:color_bg1)]($style)'

[character]

success_symbol = '[Ôê≤](bold fg:color_green)'
error_symbol = '[Ôê≤](bold fg:color_red)'
vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'
